version: 2.1

orbs:
  python: circleci/python@0.3.2

parameters:
  dependency-file:
    default: Flask_backend/requirements.txt
    description: The file to install dependencies from.
    type: string
  local:
    default: true
    description: 'Install packages for local user, not globally. Defaults to true.'
    type: boolean

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      # - python/load-cache
      # - python/install-deps
      # - python/save-cache
      # - python/test
      - restore_cache:
          key: myapp-{{ checksum "<<parameters.dependency-file>>" }}
      - run:
          command: pip install -r Flask_backend/requirements.txt
          name: Accessing python shell
      - save_cache:
          key: myapp-{{ checksum "Flask_backend/requirements.txt" }}
          paths: 
            - "Flask_backend"

workflows:
  main:
    jobs:
      - build-and-test

# jobs:
#   one:
#     docker:
#       - image: circleci/ruby:2.4.1
#     steps:
#       - checkout
#       - run: echo "Wad sup"
#       - run: sleep 15
#   two:
#     executor: python/default
#     steps:
#       - checkout
#       - python/load-cache
#       - python/install-deps
#       - python/save-cache
#       - run:
#           command: dir
#           name: Test Directory
#       - run:
#           command: ../Flask_backend/api/tests test_basic.py
#           name: Test Basic

# workflows:
#   version: 2
#   one_and_two:
#     jobs:
#       - one
#       - two:
#           requires:
#            - one

