version: 2.1

orbs:
  python: circleci/python@0.3.2
  gke: circleci/gcp-gke@1.0.4

parameters:
  dependency:
    default: Flask_backend/requirements.txt
    description: The file to install dependencies from.
    type: string
  dependency-file:
    default: requirements.txt
    description: The file to install dependencies from.
    type: string
  local:
    default: true
    description: 'Install packages for local user, not globally. Defaults to true.'
    type: boolean

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: rosbas/docker-pythonxseleniumxscrapy
    docker:
      # - image: circleci/python:3.7.2
      - image: circleci/buildpack-deps:stretch
jobs:
  build-docker:
    # executor: python/default
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      # - python/load-cache
      # - python/install-deps
      # - python/save-cache
      # - python/test
      # - restore_cache:
      #     key: myapp-{{ checksum "<< pipeline.parameters.dependency >>" }}
      - run:
          name: Building Docker image
          command: docker build -t $IMAGE_NAME:latest ./Flask_backend
      - run:
          name: Archive Docker Image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths: 
            - ./image.tar
  test:
    # executor: docker-publisher
    docker:
      - image: circleci/python:3.7.2
    steps:
      # - attach_workspace:
      #     at: /tmp/workspace
      # - setup_remote_docker
      # - run:
      #     name: Load archived Docker Image
      #     command: docker load  -i /tmp/workspace/image.tar
      - checkout
      - run:
          name: Check Directory Once
          working_directory: Flask_backend
          command: dir
      - run:
          command: |
            pip install --user -r << pipeline.parameters.dependency-file >>
          name: Installing dependency
          working_directory: Flask_backend
      - save_cache:
          key: myapp-{{ checksum "<< pipeline.parameters.dependency >>" }}
          paths: 
            - "Flask_backend"
      # - run:
      #     name: Check Directory again
      #     command: dir
      - run:
          name: Testing dummy python test.
          working_directory: Flask_backend
          command: |
            echo Running Test
            python api/tests/test_basic.py
            python test.py
            circleci-agent step halt
workflows:
  main:
    jobs:
      - build-docker:
          filters:
            branches:
              only:
                - master
                - MergeBranches
      - test:
          filters:
            branches:
              only: 
                - master
                - MergeBranches

# jobs:
#   one:
#     docker:
#       - image: circleci/ruby:2.4.1
#     steps:
#       - checkout
#       - run: echo "Wad sup"
#       - run: sleep 15
#   two:
#     executor: python/default
#     steps:
#       - checkout
#       - python/load-cache
#       - python/install-deps
#       - python/save-cache
#       - run:
#           command: dir
#           name: Test Directory
#       - run:
#           command: ../Flask_backend/api/tests test_basic.py
#           name: Test Basic

# workflows:
#   version: 2
#   one_and_two:
#     jobs:
#       - one
#       - two:
#           requires:
#            - one